### ISSUE TITLE
Private network is enabled but network is missing

### ISSUE THREAD

**Issue by nightscape** [EXASOL/docker-db#1]
Hi!

We're trying to use the `exasol/docker-db:6.0.0-d1sc` for running local tests before deploying them to the real cluster.
On some machines running the image works perfectly, on others it fails like this:

```
$ docker --version
Docker version 1.13.0, build 49bf474

docker pull exasol/docker-db:6.0.0-d1sc                                                                                
6.0.0-d1sc: Pulling from exasol/docker-db
Digest: sha256:851bdc7da8e562e99528ce1a1fcaf62ffd0c86f5ef22813751fafe7e046850bd
Status: Image is up to date for exasol/docker-db:6.0.0-d1sc

$ docker run --rm --privileged exasol/docker-db:6.0.0-d1sc                                                               
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000761793 s, 1.4 GB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000747259 s, 1.4 GB/s
Traceback (most recent call last):
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/libexec/exainit.py", line 11, in <module>
    from exainit.config import config
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/exainit/config.py", line 18, in <module>
    exaconf = EXAConf(None, True)
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/devel/docker/libexadt/EXAConf.py", line 108, in __init__
    self.validate()
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/devel/docker/libexadt/EXAConf.py", line 454, in validate
    raise EXAConfError("Private network is enabled but network is missing in section '%s'!" % section)
libexadt.EXAConf.EXAConfError: "ERROR::EXAConf: Private network is enabled but network is missing in section 'Node : 11'!"
```
What kind of network is the error message talking about? Is that a docker network?
Any other clues what might go wrong here?

Thanks!

**Comment by nightscape** [comment]
Interestingly, when I start the container with `sh` and run the `sc_init.sh` script manually (which should exactly correspond to the used `CMD ["/bin/sh" "-c" "/bin/sh /exa/etc/sc_init.sh"]`) it's working:
```docker run -it --privileged=true exasol/docker-db:6.0.0-d1sc sh
sh-4.1# /bin/sh /exa/etc/sc_init.sh
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000716441 s, 1.5 GB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000657235 s, 1.6 GB/s
[2017-04-26 15:39:53] stage0: Run stage 'stage0'
[2017-04-26 15:39:53] stage0: Run service environment_conf
[2017-04-26 15:39:53] stage0: Run service license_check
[2017-04-26 15:39:53] stage0: Run service next_stage
```

**Comment by ooke** [comment]
In `/exa/etc/sc_init.sh` exists one tricky place, which may be do not work in your configuration:
```
    14  CURIP="$(/sbin/ip addr | awk '{ if (n>0) { n+=1; } if (n==3) { print $2; n=0; } } /state UP/{ n=1; }')"
    15  sed -i "s+XXX.XXX.XXX.XXX/XX+$CURIP+" /exa/etc/EXAConf
```

It is possible, that if it starts in your envirenment, the network interface is not `UP` fast enough, it would explain, why it works if you start it manually. May be a `sleep` or a active white loop before line 14 would be good....

**Comment by nightscape** [comment]
Hi @ooke, thanks for your help!
I think you're right with your diagnose:
If I start the container and directly execute the `sc_init.sh` script (as it effectively is by the `CMD`) it fails:
```
$ docker run -it --privileged=true exasol/docker-db:6.0.0-d1sc sh /exa/etc/sc_init.sh
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000785147 s, 1.3 GB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000743975 s, 1.4 GB/s
Traceback (most recent call last):
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/libexec/exainit.py", line 11, in <module>
    from exainit.config import config
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/exainit/config.py", line 18, in <module>
    exaconf = EXAConf(None, True)
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/devel/docker/libexadt/EXAConf.py", line 108, in __init__
    self.validate()
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.0/devel/docker/libexadt/EXAConf.py", line 454, in validate
    raise EXAConfError("Private network is enabled but network is missing in section '%s'!" % section)
libexadt.EXAConf.EXAConfError: "ERROR::EXAConf: Private network is enabled but network is missing in section 'Node : 11'!"
```

If however I wait a little before running the script everything works:
```
$ docker run -it --privileged=true exasol/docker-db:6.0.0-d1sc bash -c 'sleep 3 && sh /exa/etc/sc_init.sh'                                         
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00286304 s, 366 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.000715008 s, 1.5 GB/s
[2017-04-27 11:04:55] stage0: Run stage 'stage0'
```

Directly running line 14 from `sc_init.sh` without sleeping
```
$ docker run -it --privileged=true exasol/docker-db:6.0.0-d1sc bash -c "/sbin/ip addr | awk '{ if (n>0) { n+=1; } if (n==3) { print $2; n=0; } } /state UP/{ n=1; }'"
$
```
and with sleeping
```
$ docker run -it --privileged=true exasol/docker-db:6.0.0-d1sc bash -c "sleep 3 && /sbin/ip addr | awk '{ if (n>0) { n+=1; } if (n==3) { print $2; n=0; } } /state UP/{ n=1; }'"
    inet 172.17.0.3/16 scope global eth0
$
```
