### ISSUE TITLE
CalledProcessError when trying to run stand-alone container

### ISSUE THREAD

**Issue by dixiekong** [EXASOL/docker-db#25]
Hello,

I am getting a network related error when trying to run a stand-alone container:
`docker run -p 8080:8888 --name exasoldb --privileged --stop-timeout 120 exasol/docker-db:latest`

```
Traceback (most recent call last):
File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/devel/docker/exadt", line 1429, in <module>
    main()
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/devel/docker/exadt", line 1426, in main
    command.func(command)
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/devel/docker/exadt", line 349, in init_sc
    first_if = utils.get_first_interface(timeout=15)
  File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.12/devel/docker/libexadt/utils.py", line 103, in get_first_interface
    output = subprocess.check_output(['/usr/bin/env', 'ip', 'addr'])
  File "/usr/opt/EXASuite-6/EXARuntime-6.0.12/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'ip', 'addr']' returned non-zero exit status -11
```
Version is: Docker version 18.06.1-ce, build e68fc7a

I expect the container to start but it doesn't. Thanks for your help.

[docker-inspect.txt](https://github.com/EXASOL/docker-db/files/2552632/docker-inspect.txt)

**Comment by exajuk** [comment]
Hi!

 You could try to start the container with a bash as the entrypoint and execute the failed command manually:
`docker run --rm -p 8080:8888 --name exasoldb --privileged --stop-timeout 120 --entrypoint /bin/bash -ti exasol/docker-db:latest`
and then:
`/usr/bin/env ip addr`

Alternatively, you can start the container detached (same command as yours, but with `--detach`), then open a bash inside it  (`docker exec -ti exasoldb /bin/bash`) and execute the failed command there.

Please provide the complete output of the `ip` command and also the output of `docker logs exasoldb` (for the failed startup).

**Comment by dixiekong** [comment]
Hi there and thank you for helping out,
 the output of `docker logs` is the above traceback with these two lines appearing before:
```
[2018-11-06 12:58:32] exadt:: '/exa/etc' does not exist! Doing full initialization.
[2018-11-06 12:58:32] exadt:: searching for the first interface with state UP
```
As far as I understand it the problem is that the container exits right away.
When I run the command with bash as entry point I get no error but the process finishes and I am not dropped to a shell within the container.
`docker ps -a` show:
```
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                       PORTS               NAMES
b250bb23382d        exasol/docker-db:latest   "/bin/bash"         8 seconds ago       Exited (139) 8 seconds ago                       exasoldb
```
The `docker logs exasoldb` command shows nothing.

**Comment by exajuk** [comment]
> When I run the command with bash as entry point I get no error (no traceback messag) but the process finishes and I am not dropped to a shell within the container.

Then you probably forgot the `-ti` option. Did you copy & paste the command from my comment?

**Comment by dixiekong** [comment]
Yes I did

**Comment by exajuk** [comment]
I'm sorry, but we can't help you without seeing the actual error message from `ip` :( All the commands above are working correctly in our test environment (with the same image). Maybe your network configuration is broken somehow, but that's just guessing... This is what the `ip` output looks like in a working environment:
```
juk@juk-u1:~$ docker run --rm -p 8080:8888 --name exasoldb --privileged --stop-timeout 120 --entrypoint /bin/bash -ti exasol/docker-db:latest
[root@cabb397e94ab /]# 
[root@cabb397e94ab /]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
5: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
[root@cabb397e94ab /]#
```
Hope that helps...

**Comment by exajuk** [comment]
> Thanks a lot for your support. If I ever find the solution to my problem I will let you know.

You're welcome. It's really weird that you can't even start a bash in the container. I haven't seen this problem ever before. Usually it's just a missing `-ti` if the command exits immediately (I also forget that sometimes). I'm really interested in the solution if you should ever find one...
