### ISSUE TITLE
arm64 

### ISSUE THREAD

**Issue by ganesansankara** [exasol/docker-db#63]
Trying to run this image  on Apple M1 Mac with flag --platform linux/amd64. Shows below error
Log_E: [2021-06-29 17:34:31] <274893748416> debugging.cc:610 register_signal_stack(): Could not setup signal stack : (22) Invalid argument
Traceback (most recent call last):
  File "/usr/opt/EXASuite-7/EXAClusterOS-7.0.10/libexec/exainit.py", line 10, in <module>
    from exainit.config import config
  File "/usr/opt/EXASuite-7/EXAClusterOS-7.0.10/lib/exainit/config.py", line 26, in <module>
    from exainit.tasks.initialsql import initialsql
  File "/usr/opt/EXASuite-7/EXAClusterOS-7.0.10/lib/exainit/tasks/initialsql.py", line 3, in <module>
    from libconfd.common.db_helper import DBHelper
  File "/usr/opt/EXASuite-7/EXAClusterOS-7.0.10/lib/libconfd/common/db_helper.py", line 11, in <module>
    import exacos # type: ignore
  File "/usr/opt/EXASuite-7/EXAClusterOS-7.0.10/lib/exacos.py", line 15, in <module>
    from libCOS_py3 import process_handler, logger, global_lock, thread_safe_fork_execve_and_read, thread_safe_fork_execve_and_read_write, fletcher32_2, register_log_rotation_sighandler
  File "libCOS++/interface/global_mutex_python.pxi", line 3, in init libCOS_py3
AttributeError: type object 'libCOS_py3.global_lock' has no attribute '__reduce_cython__'

**Comment by fvaasen** [comment]
I have the same issue. Are there plans to release support for arm64? Or is there another solution available?

**Comment by littleK0i** [comment]
+1 to this issue, would be nice to be able to run Exasol on M1 architecture.

It might be especially important for new potential customers willing to test Exasol locally.

**Comment by elinger** [comment]
+1

**Comment by gneeser** [comment]
> For me it runs but suddenly exits while starting without any errors and at the same place. Works fine on older Mac with Intel chipset ` [2022-04-04 13:27:17] exadt:: '/exa/etc' does not exist! Doing full initialization.
> 
> [2022-04-04 13:27:17] exadt:: searching for the first interface with state UP
> 
> [2022-04-04 13:27:17] exadt:: copying license file ''/.license.xml'' to ''/exa/etc/license.xml''
> 
> [2022-04-04 13:27:17] exadt:: initializing EXAConf
> 
> [2022-04-04 13:27:17] exadt:: using interface 'eth0@if28' with address '172.17.0.2/16'.
> 
> [2022-04-04 13:27:17] exadt:: setting hostname to 'n11'
> 
> [2022-04-04 13:27:17] exadt:: creating EXAStorage devices
> 
> [2022-04-04 13:27:17] exadt:: calling '('/usr/opt/EXASuite-7/EXARuntime-7.1.8/bin/numactl', ['--interleave=all', '/usr/opt/EXASuite-7/EXAClusterOS-7.1.8/libexec/exainit.py'])'
> 
> [2022-04-04 13:27:20] stage0: Run service init_done_marker
> 
> [2022-04-04 13:27:20] stage0: Run service license_check
> 
> [2022-04-04 13:27:20] stage0: Run service fix_permissions
> 
> [2022-04-04 13:27:20] stage0: Run service prepare_update
> 
> [2022-04-04 13:27:20] stage0: Run service node_options
> 
> [2022-04-04 13:27:20] stage0: Run service register_node
> 
> [2022-04-04 13:27:20] stage0: Run service next_stage
> 
> [2022-04-04 13:27:19] stage0: Output redirected to '/exa/logs/cored/exainit.log'
> 
> [2022-04-04 13:27:20] stage0: Current environment settings:
> 
> [2022-04-04 13:27:20] stage0: >>> [('COS_CONF_DIR', '/exa'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('COS_DIRECTORY', '/usr/opt/EXASuite-7/EXAClusterOS-7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('EXA_DB_VERSION', '7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('EXA_IMG_VERSION', '7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('EXA_NODE_ID', '11'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('EXA_OS_VERSION', '7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('EXA_RE_VERSION', '7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('HOME', '/'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('HOSTNAME', 'n11'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LANG', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_ADDRESS', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_COLLATE', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_CTYPE', 'en_US.utf8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_IDENTIFICATION', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_MEASUREMENT', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_MESSAGES', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_MONETARY', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_NAME', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_NUMERIC', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_PAPER', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_TELEPHONE', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('LC_TIME', 'C'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('MANPATH',
> 
> [2022-04-04 13:27:20] stage0: >>> '/usr/opt/EXASuite-7/EXAClusterOS-7.1.8/man:/usr/local/share/man:/usr/share/man'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('PATH',
> 
> [2022-04-04 13:27:20] stage0: >>> '/usr/opt/EXASuite-7/EXAClusterOS-7.1.8/bin:/usr/opt/EXASuite-7/EXAClusterOS-7.1.8/sbin:/usr/opt/EXASuite-7/EXARuntime-7.1.8/bin:/usr/opt/EXASuite-7/EXARuntime-7.1.8/sbin:/bin:/sbin:/usr/bin:/usr/sbin'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('PWD', '/'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('RE_PATH', '/usr/opt/EXASuite-7/EXARuntime-7.1.8'),
> 
> [2022-04-04 13:27:20] stage0: >>> ('SHLVL', '0')]
> 
> [2022-04-04 13:27:20] stage0: Successfully set timestamps of all jobs to the current date for anacron.
> 
> [2022-04-04 13:27:20] stage0: Init done marker in mode 'start' done with file '/exa/etc/init_done' done.
> 
> [2022-04-04 13:27:20] stage0: You have following license limits:
> 
> [2022-04-04 13:27:20] stage0: >>> Database memory (GiB): 10 Main memory (RAM) usable by databases
> 
> [2022-04-04 13:27:20] stage0: >>> Database raw size (GiB): 10 Raw Size of Databases (see Value RAW_OBJECT_SIZE in System Tables)
> 
> [2022-04-04 13:27:20] stage0: >>> Cluster nodes: 1 Number of usable cluster nodes
> 
> [2022-04-04 13:27:20] stage0: >>> Database mem size (GiB): unlimited Compressed Size of Databases (see Value MEM_OBJECT_SIZE in System Tables)
> 
> [2022-04-04 13:27:20] stage0: >>> Expiration date: unlimited Date of license expiration
> 
> [2022-04-04 13:27:20] stage0: Permissions fixed: nsexec
> 
> [2022-04-04 13:27:20] stage0: Current node id is '11'
> 
> [2022-04-04 13:27:20] stage0: Node could not be registered.
> 
> [2022-04-04 13:27:20] stage0: Next stage will be 'stage1'.
> 
> [2022-04-04 13:27:21] stage1: Output redirected to '/exa/logs/cored/exainit.log'
> 
> [2022-04-04 13:27:21] stage1: Run stage 'stage1'
> 
> [2022-04-04 13:27:21] stage1: Ignore service environment_conf
> 
> [2022-04-04 13:27:21] stage1: Ignore service rc_local
> 
> [2022-04-04 13:27:21] stage1: Run service node_options
> 
> [2022-04-04 13:27:21] stage1: Run service prepare_update
> 
> [2022-04-04 13:27:21] stage1: Run service timezone
> 
> [2022-04-04 13:27:21] stage1: Run service create_users
> 
> [2022-04-04 13:27:24] stage1: Run service node_etc_cos
> 
> [2022-04-04 13:27:24] stage1: Run service name_resolution
> 
> [2022-04-04 13:27:24] stage1: Run service sysctl
> 
> [2022-04-04 13:27:24] stage1: Run service hugepages_support
> 
> [2022-04-04 13:27:24] stage1: Run service diskconf
> 
> [2022-04-04 13:27:24] stage1: Run service broadcast_peers
> 
> [2022-04-04 13:27:24] stage1: Run service lvm_config
> 
> [2022-04-04 13:27:24] stage1: Run service devshm_config
> 
> [2022-04-04 13:27:24] stage1: Run service root_bashrc
> 
> [2022-04-04 13:27:24] stage1: Run service rsyslogd
> 
> [2022-04-04 13:27:24] stage1: Run service crond
> 
> [2022-04-04 13:27:24] stage1: Run service super_cored `

@anastyn I'm having the same issue. Did you ever find a resolution?

**Comment by alishaagupta** [comment]
I'm having the same issue. Do we have any solution to this?

**Comment by ramakrishna227** [comment]
Is there any solution/workaround to make Exasol container run on Mac m1. I have also tried enabling emulator but it didn't work.

**Comment by Nicoretti** [comment]
[Comment #78](https://github.com/exasol/docker-db/issues/78#issuecomment-1963550419) may be relevant to some of the issues raised in this ticket.
